订单功能
kmahyyg/shit-ssm-eshop pull request #5
Opened 2021-02-13 04:41 UTC by Yiyangqianxixxxx

实现了添加订单和删除订单的功能

2021-02-13 06:28 UTC, kmahyyg requested changes

2021-02-13 06:28 UTC, kmahyyg commented on src/main/java/xyz/kmahyyg/eshopdemo/controller/OrderController.java
> +        }else{
请删除无用的else分支，未登录用户会自动跳转，无需return login。

2021-02-13 06:28 UTC, kmahyyg commented on src/main/java/xyz/kmahyyg/eshopdemo/controller/OrderController.java
> +    @RequestMapping("/show/user/addorder")
请修改为 PutMapping，使用 http 方法标识操作类型。

2021-02-13 06:28 UTC, kmahyyg commented on src/main/java/xyz/kmahyyg/eshopdemo/controller/OrderController.java
> +                List<SysUserCart> allUserCartByUser = sysUserCartDao.selectByUserId(currentUserUid);
请修改变量名以增加代码可读性。

2021-02-13 06:28 UTC, kmahyyg commented on src/main/java/xyz/kmahyyg/eshopdemo/controller/OrderController.java
> +                    record.setGenTime(Long.valueOf(Long.toString(new Date().getTime())));
请参阅 https://www.geeksforgeeks.org/date-gettime-method-in-java-with-examples/

此方法已返回 long 对象，无需额外的 valueof 方法。

另：返回是ms级别的时间戳，数据库存储的是s级别的时间戳，请进行除法取整运算获得秒级时间戳。

2021-02-13 06:28 UTC, kmahyyg commented on src/main/java/xyz/kmahyyg/eshopdemo/controller/OrderController.java
>      @RequestMapping("/show/user/order")
请修改为 GetMapping

2021-02-13 06:28 UTC, kmahyyg commented on src/main/java/xyz/kmahyyg/eshopdemo/controller/OrderController.java
> +    @RequestMapping("/show/user/addorder")
路由保持为 /api/user/order

后端api路由统一使用 /api 并使用 restcontroller 作为类注解开头
前端页面显示路由统一使用 /show 开头，并使用 controller 注解。

自行查看类似问题并修改。

2021-02-13 06:28 UTC, kmahyyg commented on src/main/java/xyz/kmahyyg/eshopdemo/controller/OrderController.java
> +    @RequestMapping("/show/user/delorder")
请修改为 DeleteMapping 并更改路由名为/api/user/order

2021-02-13 06:28 UTC, kmahyyg commented on src/main/resources/mapper/SysItemsDao.xml
> +        <result column="status" jdbcType="INTEGER" property="status" typeHandler="org.apache.ibatis.type.EnumOrdinalTypeHandler" javaType="xyz.kmahyyg.eshopdemo.enums.ItemStatusEnum"/>
请 pull 上游并完成 merge conflict resolve 后提交。

2021-02-13 06:28 UTC, kmahyyg commented on src/main/resources/mapper/SysOrdersDao.xml
> +        values (#{oid,jdbcType=VARCHAR}, #{status.ordinal,jdbcType=INTEGER}, #{items,jdbcType=VARCHAR},
可以解释一下为什么要在这这么写吗？

请在java文件端使用 .ordinal() 方法获取。

2021-02-13 06:28 UTC, kmahyyg commented on src/main/resources/templates/userorders.html
> +<html lang="en" xmlns:th="http://www.w3.org/1999/xhtml">
xmlns th namespace 定义错误，请参考其他现有文件

2021-02-13 06:28 UTC, kmahyyg commented on src/main/resources/templates/userorders.html
> +        if(confirm("确认删除该订单吗?")==true){
1. 请不要使用潜在的保留字 del 作为函数名
2. 请不要直接拼接url，此处应当使用 form 方法配合 foreach 进行表单提交。

2021-02-13 06:28 UTC, kmahyyg commented on src/main/resources/templates/userorders.html
> +            window.location.href="delorder?orderId="+orderid;
路由地址错误，请不要使用csdn

2021-02-13 06:32 UTC, kmahyyg requested changes

2021-02-13 06:32 UTC, kmahyyg commented on src/main/java/xyz/kmahyyg/eshopdemo/dao/SysUserCartDao.java
> +    List<SysUserCart> selectByUserId(String uid);
代码逻辑错误， cart 仅表示当前用户的购物车，内容由items决定，不是使用多个cart表示。

2021-02-13 06:32 UTC, kmahyyg commented on src/main/java/xyz/kmahyyg/eshopdemo/controller/OrderController.java
> +                List<SysUserCart> allUserCartByUser = sysUserCartDao.selectByUserId(currentUserUid);
Line76 代码逻辑错误，变量命名不具有可读性，请参阅会议录屏和聊天记录查看购物车数据结构。

2021-02-13 06:32 UTC, kmahyyg commented on src/main/java/xyz/kmahyyg/eshopdemo/controller/OrderController.java
> +            sysOrdersDao.deleteOrderByOid(orderId);
请检查返回的整数以确认是否成功删除。

2021-02-13 07:49 UTC, Yiyangqianxixxxx commented on src/main/resources/mapper/SysOrdersDao.xml
> +        values (#{oid,jdbcType=VARCHAR}, #{status.ordinal,jdbcType=INTEGER}, #{items,jdbcType=VARCHAR},
java文件端的status类型是 OrderStatusEnum类型， ordinal得到的是int类型，无法给status赋值

2021-02-13 07:52 UTC, kmahyyg commented on src/main/resources/mapper/SysOrdersDao.xml
> +        values (#{oid,jdbcType=VARCHAR}, #{status.ordinal,jdbcType=INTEGER}, #{items,jdbcType=VARCHAR},
https://github.com/kmahyyg/shit-ssm-eshop/blob/514873dc261555d08d69132407a520243f265534/src/main/resources/mapper/SysOrdersDao.xml#L8

这里加了之后，这行就不需要了，请直接删除 .ordinal

2021-02-13 07:53 UTC, kmahyyg commented on src/main/resources/mapper/SysOrdersDao.xml
> +        values (#{oid,jdbcType=VARCHAR}, #{status.ordinal,jdbcType=INTEGER}, #{items,jdbcType=VARCHAR},
可以参考上一个同学的商品搜索的返回结果列表，也是用了 enum。 

Related Pull Request: PR #1

2021-02-13 08:20 UTC, Yiyangqianxixxxx commented on src/main/resources/mapper/SysOrdersDao.xml
> +        values (#{oid,jdbcType=VARCHAR}, #{status.ordinal,jdbcType=INTEGER}, #{items,jdbcType=VARCHAR},
从数据库中取出没有问题，但是将数据插入数据库时，如果不使用.ordinal这样，就无法插入数据库。

2021-02-13 08:23 UTC, kmahyyg commented on src/main/resources/mapper/SysOrdersDao.xml
> +        values (#{oid,jdbcType=VARCHAR}, #{status.ordinal,jdbcType=INTEGER}, #{items,jdbcType=VARCHAR},
那这里先不管，其他的先改了吧，最后等合并之后我查证再来改。

2021-02-13 08:24 UTC, kmahyyg commented on src/main/resources/mapper/SysOrdersDao.xml
> +        values (#{oid,jdbcType=VARCHAR}, #{status.ordinal,jdbcType=INTEGER}, #{items,jdbcType=VARCHAR},
//TODO here: fix ordinal method when inserting orders... Seems can use the same method as user or item...

2021-02-15 08:14 UTC, kmahyyg commented
Wait for future response. Closed due to inactivity in a long period of time.

2021-02-15 08:14 UTC, closed without merging